id: D4E970B0C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-04-14T12:08:27+00:00'
last_modified: '2022-05-26T12:25:33.456100+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    523f:
      image_group_id: I1PD95883
      title: རྣམ་འཇོམས་ཀྱི་སྒྲུབ་ཐབས་བརྒྱ་རྩ་བརྒྱད།
      total_pages: 1125
      order: 38
      base_file: 523f.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
